### ISSUE TITLE
Rename repo to “aries-acapy-tools"

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-acapy-tools#11]
The use “wallet” in this repo is likely confusing. How about we rename it now while it is new?

Other options:

- aries-acapy-indy-to-askar-migration
- aries-acapy-askar-migration

@dbluhm @cjhowland @andrewwhitehead — thoughts?

**Comment by andrewwhitehead** [comment]
I like aries-(a)capy-askar-migration, maybe aries-cloudagent-python-migration and then it could be reused later for other migrations.

**Comment by swcurran** [comment]
I think we use `aries-acapy-migration`.  `acapy` because we have precedence in using that for Aries Cloud Agent Python related repos, and migration for Andrew’s last point of using it again in the future if needed.  I don’t think we need to do anything now to structure for future migrations — we’ll deal with that when the time comes.

Any objections or suggestions?

**Comment by andrewwhitehead** [comment]
Another option might be `aries-acapy-tools`?

**Comment by swcurran** [comment]
Interesting. Would you suggest we restructure the repo ahead of that.  Move the `askar-wallet-upgrade` related items down a level, to leave room for more tools?

@dbluhm — would it take much effort to move things around and document accordingly?

The repo files — MAINTAINERS.md, CONTRIBUTORS.md, LICENSE.md etc. remain at the top, almost everything else moves down a level.

**Comment by dbluhm** [comment]
Nope, wouldn't be too bad to shuffle directories if we want to go that way. I think I lean towards bookmarking the repo as a good place to turn into a general tools repo but wait until we have another tool that needs a home

**Comment by swcurran** [comment]
OK — so just rename it for now.

**Comment by swcurran** [comment]
@ryjones — I don’t have the power to change the repo name — could you please do that?  `aries-acapy-tools`

Thanks

**Comment by ryjones** [comment]
@swcurran [edit this file](https://github.com/hyperledger/aries-acapy-wallet-upgrade/blob/main/.github/settings.yml)

**Comment by swcurran** [comment]
Thanks — PR submitted.  Nice!
