### ISSUE TITLE
Support for convertion of MultipleWalletSingleTable to multitenant agent using managed keys

### ISSUE THREAD

**Issue by icc-garciaju** [hyperledger/aries-acapy-tools#29]
Dear team.

Currently were holders of several wallets in indy format and we are using mwst with independent agents, and we want to move to a multitenant agent, as we know the keys of all wallets, is there any way to convert them to multi tenant?

As askar doesn't support mwst, using mwst-as-stores generates a lot of databases which require a lot more space than the original.

Thanks in advance.

**Comment by jamshale** [comment]
Closing as stale.
